In [4]:
import numpy as np

In [5]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
#matrix input using numpy
c=[]
for i in range(3):
    row = list(map(int, input("Enter row {}: ".format(i+1)).split()))
    c.append(row)
c=np.array(c)
print(c)

[[1]
 [2]
 [3]]
