In [4]:
import numpy as np

In [5]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [14]:
#matrix input using numpy 3x3
matrix = []
print("Enter the elements row-wise for a 3x3 matrix:")
for i in range(3):
    row = list(map(int, input(f"Enter row {i+1} (3 space-separated numbers): ").split()))
    matrix.append(row)

matrix = np.array(matrix)
print("Matrix is:")
print(matrix)


Enter the elements row-wise for a 3x3 matrix:
Matrix is:
[[ 4  3  2]
 [ 4 55  6]
 [ 6  5  4]]


In [15]:
'''operations on array using numpy'''
a1=np.array([1,2,3,4,5])
print("Array a1:", a1)
a2=np.array([6,7,8,9,10])
print("Array a2:", a2)

Array a1: [1 2 3 4 5]
Array a2: [ 6  7  8  9 10]


In [16]:
print(a1 + a2)  # Addition
print(a1 - a2)  # Subtraction
print(a1 * a2)  # Multiplication
print(a1 / a2)  # Division

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [23]:
a = np.arange(1, 10)  # Changed 9 to 10 to get 9 elements (1 to 9)
print("Original array:")
print(a)

reshaped = a.reshape((3, 3))  # Now reshape is valid
print("Reshaped array:")
print(reshaped)

linear = reshaped.reshape(-1)  # Flattening the matrix
print("Linear array:")
print(linear)

Original array:
[1 2 3 4 5 6 7 8 9]
Reshaped array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Linear array:
[1 2 3 4 5 6 7 8 9]
